services:
    sixpaths.twilio:
        class: Sixpaths\TwilioBundle\Client
        arguments:
            parameters:
                username: "%sixpaths.twilio.username%"
                password: "%sixpaths.twilio.password%"
                from: "%sixpaths.twilio.from%"
                spool:
                    enabled: "%sixpaths.twilio.spool.enabled%"
                    type: "%sixpaths.twilio.spool.type%"
                    directory: "%sixpaths.twilio.spool.directory%"
                    retain: "%sixpaths.twilio.spool.retain%"
                defaults:
                    to: "%sixpaths.twilio.defaults.to%"

    sixpaths.twilio.command.message.send:
        class: Sixpaths\TwilioBundle\Command\Message\SendCommand
        arguments:
            twilio: "@sixpaths.twilio"

    sixpaths.twilio.command.message.generate:
        class: Sixpaths\TwilioBundle\Command\Message\GenerateCommand
        arguments:
            twilio: "@sixpaths.twilio"
